#ifndef PJ_CONFIG_SITE_H
#define PJ_CONFIG_SITE_H

#define PJ_HAS_IPV6 1
#define PJ_HAS_SSL_SOCK 0

#define PJMEDIA_HAS_VIDEO 0
#define PJMEDIA_HAS_WEBRTC 0
#define PJMEDIA_HAS_SPEEX_AEC 0

#define PJMEDIA_HAS_G711_CODEC 1
#define PJMEDIA_HAS_G722_CODEC 1
#define PJMEDIA_HAS_OPUS_CODEC 0
#define PJMEDIA_HAS_L16_CODEC 0

#define PJSUA_MAX_CALLS 4
#define PJSUA_MAX_ACC 4

#endif
